'use client'

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Delius } from "next/font/google";
import { Dosis } from "next/font/google";
import { Analytics } from '@vercel/analytics/react';


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const dosis = Dosis({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-lora",
});

const delius = Delius({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-delius",
});

{/*export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};*/}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <body className={`${dosis.variable} ${geistMono.variable} antialiased`}>
        
          {children}
          <Analytics />
        
      </body>
    </html>
  );
}
