'use client'

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@emotion/react";
import theme from "@/components/theme";
import { CssBaseline } from "@mui/material";
import { useEffect, useState } from "react";
import { Delius } from "next/font/google";
import { Dosis } from "next/font/google";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const dosis = Dosis({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-lora",
});

const delius = Delius({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-delius",
});

{/*export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};*/}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <body className={`${dosis.variable} ${geistMono.variable} antialiased`}>
        
        
          {children}
        
      </body>
    </html>
  );
}
